server:
  port: 8081
 
    
spring:
  datasource:    url: jdbc:mysql://localhost:3306/ibm_issue?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  thymeleaf:    cache: false
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    
  mvc:
    hiddenmethod:      filter:        enabled: true

    
mybatis:
  mapper-locations:    classpath:mapper/*.xml
    
  configuration:
    map-underscore-to-camel-case: true 
    
pagehelper:  helper-dialect: mysql
  
logging:
  level:
     com.ibm.springboot.dao: debug
     
##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800
  
  