server:
  port: 8081
 
    
spring:
  datasource:    url: jdbc:mysql://localhost:3306/ibm_issue?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    
  thymeleaf:    cache: false
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    
  mvc:
    hiddenmethod:      filter:        enabled: true

    
mybatis:
  mapper-locations:    classpath:mapper/*.xml
    
  configuration:
    map-underscore-to-camel-case: true 
    
pagehelper:  helper-dialect: mysql
  
logging:
  level:
     com.ibm.springboot.dao: debug
  
  